/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Financial_Advisor_Team_MemberTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_Financial_Advisor_Team_Mea1vTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Financial_Advisor_Team_Member__c());
    }
}